version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'dev-blog.ricein.com -> http://concrete5'
      STAGE: 'local'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'
    # volumes:
    #   - "./00-proxy/default.ssl.conf.erb:/var/lib/nginx-conf/default.ssl.conf.erb"
  concrete5:
    # build: ./01-webapp
    # image: myblog
    image: 115987633364.dkr.ecr.us-east-1.amazonaws.com/myblog
    tty: true
    # ports:
    #   - '80:80'
    # cap_add:
    #   - SYS_ADMIN
    # security_opt:
    #   - apparmor:unconfined
    privileged: true
    volumes:
      - "/dev/fuse:/dev/fuse"
#    volumes:
#      - "./01-webapp/config:/etc/"